/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Process is up. No dependency is consulted, by design.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Dependencies are reachable.
         *
         *     Reports per-dependency status rather than a bare boolean, so a failing readiness check
         *     says which dependency is at fault without anyone having to read logs.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List your jobs
         * @description Newest first, cursor-paginated on the job id (ADR-0002).
         */
        get: operations["list_jobs_v1_jobs_get"];
        put?: never;
        /**
         * Submit a story for generation
         * @description Accept a job and return its id.
         *
         *     ``202``, not ``200``: the work has been accepted, not performed. A repeated
         *     ``Idempotency-Key`` returns the original job rather than queueing the same GPU work
         *     twice, and is answered ``200`` so a client can tell a replay from a fresh submission.
         */
        post: operations["create_job_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch one job
         * @description The authoritative state of a job.
         *
         *     Sufficient on its own to drive the entire UI. The WebSocket is an optimisation over
         *     polling this endpoint, never a replacement for it — which is what makes the client's
         *     polling fallback safe.
         */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel a job
         * @description Request cancellation.
         *
         *     Workers check between segments, so this actually stops GPU work rather than only
         *     relabelling the row — the thing v1 could not do at all.
         */
        delete: operations["cancel_job_v1_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/segments/{index}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Play one rendered segment
         * @description Redirect to a freshly signed URL for one segment of a job.
         *
         *     This is what makes playback start before the job finishes: the worker publishes each
         *     segment as it is rendered, and the client fetches them here by index. A stable URL
         *     rather than a signed one in the event, so the link cannot expire between being
         *     announced and being used.
         *
         *     307 rather than 302: the method must be preserved, and browsers and audio elements
         *     both follow it to the object store without a second round trip through this service.
         */
        get: operations["get_segment_audio_v1_jobs__job_id__segments__index__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available voices
         * @description Built-in voices plus the caller's own uploads.
         *
         *     Each row carries a presigned preview URL, so the picker can play a sample before the
         *     user commits to a generation.
         */
        get: operations["list_voices_v1_voices_get"];
        put?: never;
        /**
         * Upload a reference voice
         * @description Register a new voice from an uploaded audio sample.
         *
         *     Multipart, not base64-in-JSON: v1's REST proxy took the sample as a base64 string in
         *     the request body, which inflates it by a third and pushes the whole thing through the
         *     JSON parser.
         */
        post: operations["create_voice_v1_voices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voices/{voice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete your voice
         * @description Delete one of the caller's own voices. Built-ins are not deletable.
         */
        delete: operations["delete_voice_v1_voices__voice_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AudioAsset
         * @description One rendered audio file, addressed by a short-lived presigned URL.
         *
         *     Audio never travels through the API itself. v1 returned it as protobuf ``bytes``,
         *     which is why both client and server had to raise their gRPC message limit to 100 MB.
         */
        AudioAsset: {
            /** Duration Seconds */
            duration_seconds: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            format: components["schemas"]["AudioFormat"];
            /** Size Bytes */
            size_bytes: number;
            /** Url */
            url: string;
        };
        /**
         * AudioFormat
         * @description Delivery formats. MP3 is streamed to the player; WAV is offered for download.
         * @enum {string}
         */
        AudioFormat: "mp3" | "wav";
        /** Body_create_voice_v1_voices_post */
        Body_create_voice_v1_voices_post: {
            /** File */
            file: string;
            /** Name */
            name: string;
        };
        /**
         * CreateJobRequest
         * @description Body of ``POST /v1/jobs``.
         */
        CreateJobRequest: {
            /** Dialogue Voice Id */
            dialogue_voice_id?: string | null;
            /** @default neutral */
            emotion: components["schemas"]["Emotion"];
            /** @default en */
            language: components["schemas"]["Language"];
            /** @default medium */
            length: components["schemas"]["StoryLength"];
            /** @default narration */
            mode: components["schemas"]["VoiceMode"];
            /** Prompt */
            prompt: string;
            /** Second Dialogue Voice Id */
            second_dialogue_voice_id?: string | null;
            /**
             * Speed
             * @default 1
             */
            speed: number;
            /**
             * Voice Id
             * Format: uuid
             */
            voice_id: string;
        };
        /**
         * CreateJobResponse
         * @description ``202 Accepted`` body.
         *
         *     This is the whole architectural change in one shape: the caller gets an id and a
         *     place to watch, in under 200 ms, instead of holding a socket open for ten minutes.
         */
        CreateJobResponse: {
            /** Events Url */
            events_url: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * Emotion
         * @description Emotional register for the story.
         *
         *     In v1 this was passed to ``TTS.tts_to_file(emotion=...)``, which XTTS v2 accepts and
         *     ignores — the control did nothing audible. Here it conditions the *writing* instead,
         *     where it demonstrably changes the output.
         * @enum {string}
         */
        Emotion: "neutral" | "happy" | "sad" | "angry";
        /**
         * ErrorCode
         * @description Machine-readable failure reason.
         *
         *     Stored on the job row, published in the ``failed`` event, and returned in API error
         *     bodies, so the frontend can branch on the cause without parsing prose.
         * @enum {string}
         */
        ErrorCode: "validation_failed" | "prompt_too_long" | "prompt_empty" | "job_not_found" | "job_not_cancellable" | "segment_not_found" | "voice_not_found" | "voice_forbidden" | "voice_invalid_audio" | "voice_too_short" | "voice_too_long" | "voice_too_large" | "voice_name_taken" | "dialogue_voice_required" | "rate_limited" | "concurrency_limit_reached" | "daily_cap_reached" | "llm_unavailable" | "llm_timeout" | "llm_rate_limited" | "llm_content_rejected" | "story_empty" | "tts_unavailable" | "tts_timeout" | "tts_capacity" | "audio_assembly_failed" | "storage_unavailable" | "cancelled" | "internal";
        /**
         * ErrorDetail
         * @description Public description of a failure. Never carries internal detail.
         */
        ErrorDetail: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobResponse
         * @description A job as the API presents it.
         */
        JobResponse: {
            /** Audio */
            audio?: components["schemas"]["AudioAsset"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dialogue Voice Id */
            dialogue_voice_id?: string | null;
            emotion: components["schemas"]["Emotion"];
            error?: components["schemas"]["ErrorDetail"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            language: components["schemas"]["Language"];
            length: components["schemas"]["StoryLength"];
            mode: components["schemas"]["VoiceMode"];
            /** Prompt */
            prompt: string;
            /** Second Dialogue Voice Id */
            second_dialogue_voice_id?: string | null;
            /** Segment Count */
            segment_count?: number | null;
            /** Segments */
            segments?: components["schemas"]["SpokenSegment"][];
            /** Speed */
            speed: number;
            status: components["schemas"]["JobStatus"];
            /** Story Text */
            story_text?: string | null;
            timings: components["schemas"]["JobTimings"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Voice Id
             * Format: uuid
             */
            voice_id: string;
        };
        /**
         * JobStatus
         * @description Lifecycle of a generation job.
         *
         *     ``written`` is a distinct state rather than an internal detail: the story is durably
         *     persisted at that point, so a failure in the TTS stage retries synthesis alone and
         *     never re-runs the LLM.
         * @enum {string}
         */
        JobStatus: "queued" | "writing" | "written" | "synthesizing" | "done" | "failed" | "cancelled";
        /**
         * JobTimings
         * @description Per-stage timestamps.
         *
         *     The source of the v1-versus-v2 performance comparison, and of the ``/stats`` page, so
         *     the improvement is measured from real jobs rather than asserted.
         */
        JobTimings: {
            /** Finished At */
            finished_at?: string | null;
            /**
             * Queued At
             * Format: date-time
             */
            queued_at: string;
            /** Synthesizing At */
            synthesizing_at?: string | null;
            /** Writing At */
            writing_at?: string | null;
            /** Written At */
            written_at?: string | null;
        };
        /**
         * Language
         * @description Output language.
         *
         *     Restricted to the intersection of what XTTS v2 synthesises and what v1 offered. The
         *     story is written directly in this language by the LLM; v1's English-then-MarianMT
         *     round trip is gone, along with the unvalidated model-id interpolation it required.
         * @enum {string}
         */
        Language: "en" | "es" | "fr" | "de" | "it" | "ru" | "hi";
        /** Page[JobResponse] */
        Page_JobResponse_: {
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["JobResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[VoiceResponse] */
        Page_VoiceResponse_: {
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["VoiceResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * SegmentKind
         * @description Whether a slice of the story is narration or a character's spoken line.
         * @enum {string}
         */
        SegmentKind: "narration" | "dialogue";
        /**
         * SpokenSegment
         * @description One spoken segment, placed in the audio and in the story.
         *
         *     Two coordinate systems, because they are not the same text. ``start_seconds`` and
         *     ``end_seconds`` are the segment's position in the rendered track, measured by the
         *     worker that assembled it. ``start_char`` and ``end_char`` are its span in
         *     ``story_text`` — needed separately because the spoken form has been cleaned
         *     (quotes stripped, whitespace collapsed) and so cannot be located by searching.
         *
         *     Together they are what a player needs to highlight the story as it is read.
         */
        SpokenSegment: {
            /** End Char */
            end_char: number;
            /** End Seconds */
            end_seconds: number;
            /** Index */
            index: number;
            kind: components["schemas"]["SegmentKind"];
            /** Speaker */
            speaker?: string | null;
            /** Start Char */
            start_char: number;
            /** Start Seconds */
            start_seconds: number;
            /** Text */
            text: string;
        };
        /**
         * StoryLength
         * @description Requested story length.
         *
         *     A first-class field. In v1 this was a `[PARA_LEVEL:...]` marker embedded in the prompt
         *     string, parsed by substring match, and stripped back out again in three separate
         *     files — so a user who typed the marker themselves could change server-side routing.
         * @enum {string}
         */
        StoryLength: "short" | "medium" | "long";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VoiceMode
         * @description How many voices the finished audio uses.
         * @enum {string}
         */
        VoiceMode: "narration" | "narration_with_dialogue";
        /**
         * VoiceResponse
         * @description A voice in the catalogue.
         */
        VoiceResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Seconds */
            duration_seconds: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Builtin */
            is_builtin: boolean;
            /** Name */
            name: string;
            /** Preview Url */
            preview_url?: string | null;
            /** Sample Rate */
            sample_rate: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_jobs_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JobResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_v1_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_segment_audio_v1_jobs__job_id__segments__index__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_voices_v1_voices_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_VoiceResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_voice_v1_voices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_voice_v1_voices_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_voice_v1_voices__voice_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
